# Base image
FROM node:18-alpine

# Set working directory
WORKDIR /app

# Define build arguments
ARG VITE_SAVECONNECTS_SERVER_URL
ARG VITE_FIREBASE_API_KEY
ARG VITE_FIREBASE_AUTH_DOMAIN
ARG VITE_FIREBASE_PROJECT_ID
ARG VITE_FIREBASE_STORAGE_BUCKET
ARG VITE_FIREBASE_MESSAGING_SENDER_ID
ARG VITE_FIREBASE_APP_ID
ARG VITE_SAVECONNECTS_FRONT_URL

# Set environment variables
ENV VITE_SAVECONNECTS_SERVER_URL=$VITE_SAVECONNECTS_SERVER_URL
ENV VITE_FIREBASE_API_KEY=$VITE_FIREBASE_API_KEY
ENV VITE_FIREBASE_AUTH_DOMAIN=$VITE_FIREBASE_AUTH_DOMAIN
ENV VITE_FIREBASE_PROJECT_ID=$VITE_FIREBASE_PROJECT_ID
ENV VITE_FIREBASE_STORAGE_BUCKET=$VITE_FIREBASE_STORAGE_BUCKET
ENV VITE_FIREBASE_MESSAGING_SENDER_ID=$VITE_FIREBASE_MESSAGING_SENDER_ID
ENV VITE_FIREBASE_APP_ID=$VITE_FIREBASE_APP_ID
ENV VITE_SAVECONNECTS_FRONT_URL=$VITE_SAVECONNECTS_FRONT_URL

# Copy package.json and install dependencies
COPY package.json .
RUN npm install

# Install 'serve' globally
RUN npm i -g serve

# Copy the rest of the application
COPY . .

# Build the application
RUN npm run build

# Expose port 3000
EXPOSE 3000

# Serve the application
CMD [ "serve", "-s", "dist" ]