name: Deploy SaveConnects Frontend

on:
  push:
    branches:
      - staging
      - develop-qa
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
            sudo curl -L "https://github.com/docker/compose/releases/download/v2.17.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build Docker Image using Docker Compose
        run: |
          docker-compose build

      - name: Tag and Push Docker Image to Docker Hub
        env:
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        run: |
          echo $DOCKER_HUB_ACCESS_TOKEN | docker login -u $DOCKER_HUB_USERNAME --password-stdin
          docker tag saveconnects-frontend:latest $DOCKER_HUB_USERNAME/save-connects:frontend
          docker push $DOCKER_HUB_USERNAME/save-connects:frontend

      - name: Connect with VPS and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            mkdir -p /home/tishan/apps/SaveConnects
            cd /home/tishan/apps/SaveConnects

            echo "Stopping frontend container..."
            docker-compose stop frontend

            echo "Pulling latest frontend Docker image..."
            docker-compose pull frontend

            echo "Restarting the frontend service..."
            docker-compose up -d frontend

            echo "Cleaning up unused Docker images..."
            docker image prune -f

            echo "Deployment successful."
