name: Deploy SaveConnects Frontend

on:
  push:
    branches:
      - staging
      - Develop-qa
      - master

jobs:
  deploy_qa:
    if: github.ref == 'refs/heads/Develop-qa'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Connect with VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            mkdir -p /home/tishan/apps/save-connects/frontend
            cd /home/tishan/apps/save-connects/frontend

            if [ -d ".git" ]; then
              git reset --hard HEAD
              git pull origin Develop-qa
            else
              git clone -b Develop-qa git@github.com:HashBaze/SaveConnects-UI.git .
            fi

            npm install --force
            npm run build

            pid=$(pm2 pid "save-connects frontend" 2>/dev/null)
            if [ -n "$pid" ]; then
              echo "Reloading application"
              pm2 reload "save-connects frontend"
              pm2 save
            else
              echo "New application"
              pm2 start npm --name "save-connects frontend" -- start
              pm2 startup
              pm2 save
            fi
