name: Deploy SaveConnects Frontend

on:
  push:
    branches:
      - staging
      - develop-qa
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: |
          docker build -t save-connects:frontend .

      - name: Push Docker image to Docker Hub
        env:
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        run: |
          echo $DOCKER_HUB_ACCESS_TOKEN | docker login -u $DOCKER_HUB_USERNAME --password-stdin
          docker tag save-connects:frontend $DOCKER_HUB_USERNAME/save-connects:frontend
          docker push $DOCKER_HUB_USERNAME/save-connects:frontend

      - name: Connect with VPS and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            mkdir -p /home/tishan/apps/SaveConnects
            cd /home/tishan/apps/SaveConnects

            echo "Stopping frontend container..."
            docker-compose stop frontend

            echo "Pulling latest frontend Docker image..."
            docker-compose pull frontend

            echo "Restarting the frontend service..."
            docker-compose up -d frontend

            echo "Cleaning up unused Docker images..."
            docker image prune -f

            echo "Deployment successful."
